### ISSUE TITLE
why callback is bytearray,not response

### ISSUE THREAD

**Issue by spritecn** [theelous3/asks#104]
if response,any thing can bo done with callback

**Comment by theelous3** [comment]
https://asks.readthedocs.io/en/latest/idioms.html#handling-response-body-content-downloads-etc

Callbacks are used to process byte chunks as they come in from the stream. Your callback must take the chunk as an arg, and can do whatever it wants with it.

I don't know your use case, but I would probably recommend setting `stream=True` and using the stream response instead :)

**Comment by spritecn** [comment]
like this
`await g.spawn(searchDataPost,s,proSearchUrl,searchRequestData,cookiesDict,i)`
we must make a func  searchDataPost to  save response,if can use callback to do it,we can use
'await g.spawn(s.post(url,data,cookies,callback=saveResponse))'

**Comment by theelous3** [comment]
Just use stream responses:

https://asks.readthedocs.io/en/latest/overview-of-funcs-and-args.html#streaming-response-data

**Comment by spritecn** [comment]
```
async def searchDataPost(s,url,data,cookies,page):
    _r = await s.post(url,data=data,cookies=cookies)
    propertyIdPageList.append(_r.json()['pIdArr'])
```
just want to get json,no stream

**Comment by theelous3** [comment]
Can you explain your problem more completely?

**Comment by spritecn** [comment]
thanks,sorry a bout my poor english, look,i
```async def saveResponse(response):
             idList.append(_r.json()['pIdArr'])
```
i try to callback it
```await g.spawn(s.post(url,data,cookies,callback=saveResponse)```

so,its not wokrs,tell me callback arg is bytearray not response
so...

**Comment by theelous3** [comment]
If that's all you want to do, you don't need a callback or a stream response. You just need to make normal calls.

https://asks.readthedocs.io/en/latest/idioms.html

You see that first example? Like that, but use a task group.

We have a worker function. Its job is only to act as a coroutine we can spawn with our task group so it can make a request for us.

We can use that same approach, except return `r` or `r.json()` and append that to a list. We don't need to handle the body in any kind of streaming or callback way. Just simple, like you would with requests.

I don't know if you're using curio or trio, but you can iterate their task groups and extract results from their tasks. This would be the best way of doing it.
