### ISSUE TITLE
Typo in readthedocs.io page

### ISSUE THREAD

**Issue by trevorwelch** [theelous3/asks#110]
Just wanted to let you know in the docs ( https://asks.readthedocs.io/en/latest/ ) there's a little typo in this paragraph:

> If you like async, but don’t like the spaghetti-docs **furture**-laden many-looped asyncio lib, you’ll probably love curio and trio. If you wish you could marry them with requests, you’ll probably love asks.

I'm assuming the author meant _future-laden_. 

<3

**Comment by theelous3** [comment]
Here you go you lunatic!

https://github.com/theelous3/asks/commit/e62b951805a81e156ea8380352113878d6470d30

ty :)
