### ISSUE TITLE
Ability to set raw HTTP body of request.

### ISSUE THREAD

**Issue by l0x-c0d3z** [theelous3/asks#111]
Hi.
We have a use case where we need to send a custom http body in the request.

We're thinking about adding a `body=` kwarg to `RequestProcessor`, and extending `_formulate_body` accordingly. Is this the proper way to do so ? Is there maybe an easier way that I am missing ?

Thanks for your insight.

**Comment by theelous3** [comment]
Not at a computer right now, but looks like you might just want to do like,
body=your_http_as_string ?

**Comment by l0x-c0d3z** [comment]
Yes, this is precisely what we have in mind.

**Comment by theelous3** [comment]
This is already what happens:

```python
import asks
import curio

asks.init(curio)

async def main():
    r = await asks.get('http://httpbin.org/anything', data='<html> blah </html>')
    print(r.text)

curio.run(main)
```


Results in:

```
(env) wrk :: test_envs/dashboard/dashboard ꗝ  python x.py       
{
  "args": {}, 
  "data": "<html> blah </html>", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Content-Length": "19", 
    "Content-Type": "text/plain", 
    "Host": "httpbin.org", 
    "User-Agent": "python-asks/2.2.0"
  }, 
  "json": null, 
  "method": "GET", 
  "origin": "89.101.131.120, 89.101.131.120", 
  "url": "https://httpbin.org/anything"
}
```

**Comment by l0x-c0d3z** [comment]
Ah, I see.
We do set our own header by the way. Our confusion came from the doc ( https://asks.readthedocs.io/en/latest/overview-of-funcs-and-args.html#passing-queries ) that shows encoded data "in the request body'. We were assuming data was in a HTTP body, but it doesn't  make sense since it's actually a get request. We are already setting a custom content-type, by the way.

Thanks a lot for your quick help. I'm closing the issue.

**Comment by theelous3** [comment]
Ah, haha. Apologies. Most of the http sites sites don't care about method, and treat gets/posts the same as you can see in my example from just a few mins ago.

I'll fix the docs so that gets and posts are used appropriately.

Yes, `params` is for query strings in gets/posts, and `data` is for request body in posts, be that json, strings or bytes. Thanks for pointing that out.
