### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by carlwgeorge** [theelous3/asks#122]
Please add git tags that correspond to the appropriate release on PyPI.

**Comment by theelous3** [comment]
Sure thing.

**Comment by carlwgeorge** [comment]
Still not seeing any [tags](https://github.com/theelous3/asks/tags).

**Comment by carlwgeorge** [comment]
I see the tag now, thanks!

**Comment by theelous3** [comment]
yw! Sorry for delay :)

I'm now much more free to work on things, thankfully, so we'll be seeing some nice improvements over the next few weeks.
