### ISSUE TITLE
asks mishandles redirection when a non-standard location is received

### ISSUE THREAD

**Issue by Spyder-exe** [theelous3/asks#131]
While working on a project with asks, I found a bug where asks would mishandle a redirection and return a different response than urllib or aiohttp would for the same request. Details can be found here : #130 

Thanks to help of the lovely folks over at StackOverflow, we managed to see where the issue was coming from, this seems to be a bug with how asks handles redirection when a non-standard location is received.

The server returns a 302 redirection with `Location: inquiry.asp?...` while asks expects it to be a full URL.

**Comment by theelous3** [comment]
Oh, interesting. Nice catch. I'll look in to this.
