### ISSUE TITLE
Add helper function for HTTP PATCH request

### ISSUE THREAD

**Issue by ducdetronquito** [theelous3/asks#139]
Hello !

Currently there is no helper function (like `get`, `post`, `put`, etc...) for HTTP PATCH requests.

Would it be possible to add one ?

Thanks :)

**Comment by theelous3** [comment]
Haha!

Wow, goes to show how lazy we all are about http verbage. Like, three years and nobody noticed. Nice one.

**Comment by ducdetronquito** [comment]
Sometimes we dont see what's just under our nose ;)

Thanks for merging this, we will use it in production straight away 👌 

Have a nice day !
