### ISSUE TITLE
Cyrillic error

### ISSUE THREAD

**Issue by wku** [theelous3/asks#15]
import asks
import curio

async def grabber(path, s):
    print ('grabber',path, s)
    r = await s.get(path=path)
    print (r.content)

async def main():
    path_list = ['/?cyrillic=ЛОРПЛОПР']
    #path_list = ['/?non_cyrillic=HGJHGJHG']
    s = asks.HSession(host='https://example.org')
    for path in path_list:
        await curio.spawn(grabber,path, s)

curio.run(main())

...
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_util.py", line 119, in bytesify
    s = s.encode("ascii")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-18: ordinal not in range(128)

> h11 They also wrote about the error

**Comment by theelous3** [comment]
Not a bug, It is a requirement of the http protocol that characters be ascii only. This means that you cannot use cyrillic or any other non-ascii character in a url.

However!

You may notice that if you visit a .ru website however, in your browser, that you see cyrillic characters in the address bar. This is just the browser being nice to you and displaying an encoded path in plaintext.

The workaround is to convert your non-ascii in to utf-8 bytestrings and insert them as % formatted hex values, much like you would see "%20" for a space.
