### ISSUE TITLE
json parameter bug

### ISSUE THREAD

**Issue by remdragon** [theelous3/asks#175]
Asks 2.4.10
Python 3.8.5

There is a small bug in asks/request_obj.py

submitting a value of {} for the json parameter causes it to not be recognized as a json body

asks/request_obj.py line 194 reads:

```        if any((self.data, self.files, self.json, self.multipart is not None)):```

but it should read:

```        if any((self.data, self.files, self.json is not None, self.multipart is not None)):```

I suspect a similar change may be necessary for self.data and self.files, but I don't have any scenarios that I can present to make that case.

**Comment by derfred** [comment]
Same happens if submitting an empty array `[]` for the json parameter.

**Comment by theelous3** [comment]
I've merged the suggested change here: https://github.com/theelous3/asks/pull/177

Tbh, though asks wasn't handling this gracefully, I don't think it's a good idea to go around sending empty structures as json. However, given people build all sorts of crazy shit with json, I'll allow it. I don't think I'll extend this to data/files without pretty good reason though.
