### ISSUE TITLE
Requires trio/curio but neither are listed in dependencies

### ISSUE THREAD

**Issue by SunDwarf** [theelous3/asks#24]
Issue is as in title. They should be listed in dependencies, or the relevant wrappers imported inside functions to prevent failure when one is not installed.

**Comment by theelous3** [comment]
Oh dear. Missplaced that import horribly. Thanks!

**Comment by theelous3** [comment]
Fixed [here](https://github.com/theelous3/asks/commit/e7955c21b6bf89d63d6822347d7502e5d38bab35) and updated on pypi. Thanks!

**Comment by SunDwarf** [comment]
Thanks for the really speedy response, too!
