### ISSUE TITLE
Error when working with cookies

### ISSUE THREAD

**Issue by wku** [theelous3/asks#29]
import asks
import curio
asks.init('curio')
from asks.sessions import Session

async def hsession_t_stateful(s):
&nbsp;&nbsp;&nbsp;&nbsp;r = await s.get()
&nbsp;&nbsp;&nbsp;&nbsp;assert r.status_code == 200

async def main():
&nbsp;&nbsp;&nbsp;&nbsp;s = Session('https://google.ie', persist_cookies=True)
&nbsp;&nbsp;&nbsp;&nbsp;async with curio.TaskGroup() as g:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for _ in range(2):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;await curio.spawn(hsession_t_stateful(s))

curio.run(main())

"""
...
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/cookie_utils.py", line 34, in _check_cookies
    return self._get_cookies_to_send(relevant_domains)
  File "/home/wku/anaconda3/lib/python3.6/site-packages/asks/cookie_utils.py", line 46, in _get_cookies_to_send
    cookies_to_go[cookie_obj.name] = cookie_obj.value
AttributeError: 'str' object has no attribute 'value'
...

"""

**Comment by yifeikong** [comment]
please format your code, or no one could help you

**Comment by theelous3** [comment]
Hi wku, I'm working on a fix for this at the moment. I'll push it over the next day or so. Thanks for raising it :)

For future refrence, you can format code by wrapping it in tripple backticks  `  like so:

```python
some_code = lambda x: x + 'lol'
```

**Comment by theelous3** [comment]
Alright, this is fixed [here](https://github.com/theelous3/asks/commit/1b203e8a04816165466943618367d721399ccf98), and some further fixes were required after that, which took place [here](https://github.com/theelous3/asks/commit/58d147ca39bf6ea3545384217ca8a57d2643318f).

Thanks once again for the feedback @wku :)

**Comment by wku** [comment]
Yes fine
If you still solve the problem with the proxy, it would be just great)

**Comment by theelous3** [comment]
@wku yep, that's something that needs working on!
