### ISSUE TITLE
Error with trio

### ISSUE THREAD

**Issue by lormayna** [theelous3/asks#31]
I'm using Debian experimental with a virtualenv.

This is the error that I got:

`$ python
Python 3.6.2 (default, Aug  4 2017, 14:35:04)
[GCC 6.4.0 20170724] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trio
>>> import asks
>>> asks.init('trio')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lorenzo/project/football_prediction/lib/python3.6/site-packages/asks/__init__.py", line 76, in init
    _async_lib.aopen = trio.open_file
AttributeError: module 'trio' has no attribute 'open_file'
`

**Comment by Zaab1t** [comment]
Which version of trio are you using?

**Comment by Zaab1t** [comment]
AFAIK you need the development branch of trio atm:
```pip install git+https://github.com/python-trio/trio.git```

**Comment by theelous3** [comment]
@Zaab1t is correct. Trio's development branch supports async file i/o, but the version on pypi does not. I think the api is still slightly in flux at the moment.
