### ISSUE TITLE
Would it be hard to add support for python 3.5?

### ISSUE THREAD

**Issue by njsmith** [theelous3/asks#39]
I'm looking at using `asks` in the trio tutorial, and it's a little awkward to be like "so before starting, make sure you have trio, which works on cpython 3.5+ or pypy3, except for this part of the tutorial, to run the examples using `asks`, cpython 3.5 and pypy3 don't work, you need cpython 3.6+". It's not a huge deal if it's hard to fix, but I thought I'd at least check :-).

From a quick skim I see one use of async generators in `asks.response_objects.StreamBody`, which looks easy enough to fix. Is there anything else?

**Comment by njsmith** [comment]
It turns out there were a few things, but it wasn't that hard :-)

**Comment by theelous3** [comment]
Heh. You work quickly. I saw the issue in gmail and was popping open the editor to take a look. Beat me to it by a long shot!
