### ISSUE TITLE
Spaces in URL are not being replaced with %20

### ISSUE THREAD

**Issue by Kilavagora** [theelous3/asks#47]
Asks does not correctly handle query strings (or paths) with spaces.

I was testing internal application that was containing the query string in the Location header:

```...&response_type=code id_token token&...```

asks followed the redirect but the server gave an error response. 

Requests worked fine. When I compared, requests replaces spaces with %20 with
[requote_uri](https://github.com/requests/requests/blob/2872f17ab86583294907af84b9c36e63cd9a91ad/requests/utils.py#L524).

**Comment by theelous3** [comment]
Huh. I'll look in to this. Currently it's using `urllib.parse.quote` but something mustn't be correct.

**Comment by Kilavagora** [comment]
I might be missing something, but at the first glance the issue seems comes from here, path and query do not get quoted if params is not set: https://github.com/theelous3/asks/blob/6f72bbcb2feba8048ee4592e116c6d4ff95186ad/asks/request_object.py#L277

**Comment by theelous3** [comment]
God that whole file is so disgusting. Needs a rewrite soon!

Yes, that looks to be the culprit, going to wangjangle it now.

**Comment by theelous3** [comment]
Give latest mater a go, see if it's resolved for you.

Can install with `pip3 install git+https://github.com/theelous3/asks.git`

**Comment by Kilavagora** [comment]
Thank you, this fixed my original issue, but now seems it's broken for already quoted URLs. 

In requests it it first unquotes the URL, so that query string something like, 
```
/unquoted path/quoted%20path/index?query1=partially quoted%20value&query2=query with spaces
```
goes to
```
/unquoted path/quoted path/index?query1=partially quoted value&query2=query with spaces
```
and then eventually to
```
/unquoted%20path/quoted%20path/index?query1=partially%20quoted%20value&query2=query%20with%20spaces
```
Also, when params are present, I assume path needs to be requoted still.

**Comment by theelous3** [comment]
Ah! How about now? :D

**Comment by Kilavagora** [comment]
https://github.com/theelous3/asks/blob/60dc7ea663d3659c32936196bafcb769f3e977bb/asks/request_object.py#L280
:P

Perfect!

But what about the case below?
```python
r = await asks.get('www.example.com/some path/with%20partial%20quotes/', params={'Elmo': 'wants data'}))
```

**Comment by theelous3** [comment]
Heh, yeah. Just bashing them up at the moment. Running around headless-chicken style irl. The print will die, I promise.

`/some%20path/with%20partial%20quotes/?Elmo=wants%20data`

:D 

try now!

**Comment by Kilavagora** [comment]
Awesome, works for all my use cases. But I believe that will break now for
```python
r = await asks.get('www.example.com', params={'Elmo': 'wants data with / and ? other weird characters'})
```

**Comment by theelous3** [comment]
Oh you wonderful nightmare :D

How about now? All presented cases coming out identical to requests, and regular tests gucci.

**Comment by Kilavagora** [comment]
```python
r = await asks.get('www.example.com', params={'What if Elmo has / in the name?': 'Values seem OK'})
```

**Comment by theelous3** [comment]
Can I actually marry you?

**Comment by theelous3** [comment]
```python
>>> import asks
>>> import curio
>>> asks.init('curio')
>>> 
>>> from asks.request_object import Request
>>> 
>>> async def wat():
...     p = await asks.get('http://www.example.com/some path/with%20partial%20quotes/', params={'Elmo? wtf /%': 'wants /??% data'})
...     print('url:', p.url)
... 
>>> curio.run(wat)
"url: http://www.example.com/some path/with%20partial%20quotes/some%20path/with%20partial%20quotes/?Elmo%3F+wtf+%2F%25=wants+%2F%3F%3F%25+data"
```

Surely you cannot point out another obvious flaw.

**Comment by Kilavagora** [comment]
OK, I will close this one...
