### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by theelous3** [theelous3/asks#49]
Tests are phenomenally slow. Actual performance seems fine.

Investigate!

```
┌─╼[~/zoo/python/asks/tests] [master*] 
└────╼ pytest --tb=short
============================================== test session starts ==============================================
platform linux -- Python 3.6.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/tl3/zoo/python/asks, inifile:
plugins: httpbin-0.3.0
collected 56 items                                                                                               

test_asks_curio.py ..........................
test_asks_trio.py ..........................
test_request_object.py ..
test_response_objects.py ..

========================================== 56 passed in 117.17 seconds ==========================================
```

**Comment by theelous3** [comment]
[Looking at the build history](https://travis-ci.org/theelous3/asks/builds), can see a huge jump in travis build times starting with merge of #37 

@raylu any initial ideas as to what may have caused it? Looks to be hanging most around the session tests.

**Comment by raylu** [comment]
my guess is the two jumps are from running/tearing down httpbin locally a bunch and from turning on 2 more python envs in travis

travis is showing you the total time spent (sum of parallel test runs), not the wall clock time spent

**Comment by theelous3** [comment]
Fixed in https://github.com/theelous3/asks/commit/4b48b9a41fd6c8c5a74fd3ffe60af2c87638af69
