### ISSUE TITLE
Duplicate path in response.url

### ISSUE THREAD

**Issue by Kilavagora** [theelous3/asks#50]
OK, now I am getting the odd URLs from
```python
response = await session.get(initial_url_that_will_redirect)
print(response.url)
```
```
https://example.com/identity/login?signin=61a17533a7d449728bb90790e31dc186/identity/login?signin=61a17533a7d449728bb90790e31dc186'
```
The issue seems comes from here:
https://github.com/theelous3/asks/blob/e1ecb403e05d30222b8ab124822e236e414be139/asks/request_object.py#L530

Perhaps, self.host should be defined and the line should be something like:
```python
'url': self.host + self.path
```

**Comment by theelous3** [comment]
Yeah, I sort of bashed that in as a placeholder, because I sometimes a url is given that ends in /, and a path is given that starts with /, resulting in a url with // halfway.

Just need to write a slightly more verbose check for that.

**Comment by theelous3** [comment]
Fixed in https://github.com/theelous3/asks/commit/b078ac70545b17432156cf5aaddb668ea62ecd89

**Comment by Kilavagora** [comment]
For the above, I am getting URL that is missing https:// now:
```
example.com/identity/login?signin=61a17533a7d449728bb90790e31dc186
```

**Comment by theelous3** [comment]
Updated in https://github.com/theelous3/asks/commit/5b225abb60e6fefbf644efa3eb7040b7b52f07c4
