### ISSUE TITLE
Passing string to ask.get() with ;

### ISSUE THREAD

**Issue by JK87iab** [theelous3/asks#59]
Hi, 
I am trying to use asks for OSRM server requests.

I am sending a list of urls to my server.

Small example:

```

 async def main():
  r = await asks.get('http://35.204.249.209:5000/route/v1/driving/-73.62818000,40.75193800;-73.6356926,40.7418803?overview=simplified')
  print(r)
      
      
curio.run(main())
```
 

results in a bad request, because the OSRM server only gets 

`[info] 15-03-2018 15:54:39 0.064683ms 54.89.111.179 - python-asks/1.3.10 400 /route/v1/driving/-73.62818000,40.75193800?overview=simplified`

And if I replace the `;` with something else the OSRM gets the full URL (but of course its not working)

```
async def main():
  r = await asks.get('http://35.204.249.209:5000/route/v1/driving/-73.62818000,40.75193800%TEST-73.6356926,40.7418803?overview=simplified')
  print(r)
      
      
curio.run(main())
```

results in `[info] 15-03-2018 15:59:10 0.110487ms 54.89.111.179 - python-asks/1.3.10 400 /route/v1/driving/-73.62818000,40.75193800%TEST-73.6356926,40.7418803?overview=simplified`

What is the problem with passing ; in an URL?

EDIT:

If I replace `;` with `%3B` it works, is there an option for automatic encoding?

**Comment by theelous3** [comment]
This should be handled. I'll look in to it over the weekend and whip it up. Will prob just refactor that whole area tbh, it's a shitshow as is.

**Comment by theelous3** [comment]
Ok, `;` is a reserved character, as stated in [rfc 3986](https://tools.ietf.org/html/rfc3986#section-2.2)

So, you have two options:
    1. Encode them yourself
    2. Follow spec and fix the recipient so that it complies with the rfc.

**Comment by theelous3** [comment]
New code as of https://github.com/theelous3/asks/commit/dfc708a764fa2afd80e6743e8c2b2431f33f880c outputs:

```python
>>> import asks
>>> import curio
>>> asks.init('curio')
>>> 
>>> async def wat():
...     r = await asks.get('http://httpbin.org/get/-73.62818000,40.75193800;-73.6356926,40.7418803?overview=simplified')
...     print('url', r.url)
... 
>>> curio.run(wat)
url http://httpbin.org/get/-73.62818000,40.75193800;-73.6356926,40.7418803?overview=simplified
```
