### ISSUE TITLE
asks is not decoding the response when streaming

### ISSUE THREAD

**Issue by miracle2k** [theelous3/asks#62]
It seems it is currently not supported to have the library decode a streaming gzip response.

**Comment by theelous3** [comment]
Will check this over the weekend :)

Thanks!

**Comment by theelous3** [comment]
Ah. Finally some free time.

So, decoding gz on the fly in streams doesn't seem like a good idea.

One, you can't decode a partial chunk of gz. We can't gaurantee every server will gz each chunk it sends, resulting in a bunch of errors.

Two, there is no reason for asks to presume you want to decompress the file at any point in time, bar when you specifically call for a non streaming responses content or text.

Thoughts?

**Comment by theelous3** [comment]
Settling on my above response.

**Comment by raylu** [comment]
here's a server that sends data with gzip+chunked transfer encoding:
```python
#!/usr/bin/env python3

import socket
import time
import zlib

def main():
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
	s.bind(('', 8000))
	s.listen(4)
	while True:
		conn, addr = s.accept()
		handle(conn)

def handle(conn):
	print('<-\n' + conn.recv(4096).decode('utf-8'))
	headers = [
		'HTTP/1.1 200 OK',
		'Content-Type: text/plain',
		'Transfer-Encoding: gzip, chunked',
	]
	send(conn, ('\r\n'.join(headers) + '\r\n\r\n').encode())
	time.sleep(0.1)

	compress = zlib.compressobj(level=0, wbits=9)
	for i in range(4):
		chunk = compress.compress(b'a' * 100)
		if len(chunk) > 0:
			send_chunk(conn, chunk)
			time.sleep(0.1)
	send_chunk(conn, compress.flush())
	send_chunk(conn, b'')
	conn.close()

def send(conn, data):
	print('->\n', data)
	conn.send(data)

def send_chunk(conn, chunk):
	send(conn, hex(len(chunk))[2:].encode() + b'\r\n' + chunk + b'\r\n')

if __name__ == '__main__':
	main()
```
which works if you `curl localhost:8000`
you can decode the response in chunks (this client is super-garbage and relies on a lot of quirks to work):
```python
#!/usr/bin/env python3

import socket
import zlib

def main():
	conn = socket.create_connection(('localhost', 8000))
	conn.send(b'meh')
	headers = conn.recv(1024) # I sure hope this is only the headers
	decompress = zlib.decompressobj()
	while True:
		raw = conn.recv(1024)
		if not raw:
			break
		print('<-', raw)

		hex_length, chunk, other = raw.split(b'\r\n', 2)
		data = decompress.decompress(chunk)
		print('decompressed:', data)
	data = decompress.flush()
	print('decompressed:', data)

if __name__ == '__main__':
	main()
```

**Comment by miracle2k** [comment]
My apologies for not finding the time to reply earlier. I don't have any evidence to provide right now, but I do believe that libraries such as `requests` do support this, and do so by default.

If a server is setting the encoding header to gzip, then it would have to encode every chunk of data accordingly.

**Comment by theelous3** [comment]
I'll take a look at what requests does and see if it all adds up :)

**Comment by theelous3** [comment]
Afair requests is built entirely on urllib3, and credit is given :)

Off the top of my (pounding hangover) head, the easiest way to sort this out is to make the `Content-Encoding` header available to the `StreamBody` obj that replaces the regular body in streaming mode, or something similar, and factor out `Response._decompress` for use in both `Response`s and `StreamBody`s.

Starting a new branch for it now :D

As you pointed out @dd-dent, we shouldn't use the stream thing, as it's blocking. Thankfully decompression is pretty straight forward and can just be applied to correctly formed chunks, and isn't a blocking concern.

**Comment by dd-dent** [comment]
> ...isn't a blocking concern.
Nice pun :)

**Comment by theelous3** [comment]
This is being worked on over here:

https://github.com/theelous3/asks/tree/stream_decompression

So far so good. Going to test it out some more tomorrow and merge.

**Comment by theelous3** [comment]
Fixed, merged, and pushed to pypi.

**Comment by theelous3** [comment]
Sure, I'll add `disable_decompression`

**Comment by theelous3** [comment]
Fixed, pypi'd. You can set `StreamBody.decompress_data` to `False`. Example here in docs:

http://asks.readthedocs.io/en/latest/the-response-object.html#view-body-text-decoded-content-raw
