### ISSUE TITLE
HEY USERS :D UPDATE YOUR MULTIO BEFORE POSTING .CLOSE() ISSUES :D

### ISSUE THREAD

**Issue by theelous3** [theelous3/asks#71]

**Comment by Zaab1t** [comment]
`multio` is one of `asks`' dependencies. You can update to the newest version with `pip install --upgrade multio` from your asks environment. If you have a version specified in your `requirements.txt` (or something alike), you can fix the issue by specifying (multio) version 0.2.3 or greater.

**Comment by theelous3** [comment]
I was very drunk last night and as my little sleepy head hit the pillow I thought...

"...setup.py"

**Comment by theelous3** [comment]
New version pushed fixing this automatically, however leaving this up for a week or so.
