### ISSUE TITLE
Can asks add HOST parameters automatically?

### ISSUE THREAD

**Issue by hnyaoqingping** [theelous3/asks#73]
I connect to chromium's debug port
resp = await asks.get("http://127.0.0.1:9222")
print(resp.text)
I see result is:
'Host header is specified and is not an IP address or localhost.'
then I modity code to:
resp = await asks.get("http://127.0.0.1:9222", headers={"HOST":"127.0.0.1:9222"})
print(resp)
I see correct result:
<Response 200 OK>

Can asks add HOST parameters automatically?
I using requests.get, no problem!

**Comment by theelous3** [comment]
That's...weird. It should be doing this already. I'll investigate in a few mins. Coffee beckons :)

**Comment by theelous3** [comment]
Try the latest master :)
