### ISSUE TITLE
No option to ignore SSL/TLS certificate verification like request's verify=False

### ISSUE THREAD

**Issue by ric2b** [theelous3/asks#74]
For local development it's useful to be able to ignore invalid certificates.
Requests allows this [via a keyword argument to a request](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) (`verify=False`). It's not ideal, it still prints warnings to the console which can only be disabled in a very ugly way, at least from what I recall.

I tried to do the same with an asks request, since the API is so similar, but no luck, I can't get a request to be made if the certificate fails verification.

I think it's a useful feature that doesn't seem hard to implement, if you agree but prefer to work on other features I can take a crack at it during the weekend and send you a pull request.

**Comment by theelous3** [comment]
By all means take a crack at it! Take a crack at everything :D

I'll look in to it myself too. Check the repo for a branch for this if you haven't started before the weekend in case I've begun :)

**Comment by jamesmallen** [comment]
Strange timing! I just ran into this need for myself. It looks like first of all, multio needs to support passing a context in open_connection. I'm going to work on that right now

**Comment by smurfix** [comment]
While you're at it: a missing certificate results in an `UnboundLocalError`.
```
  File "/usr/lib/python3/dist-packages/asks/sessions.py", line 222, in request
    return r
UnboundLocalError: local variable 'r' referenced before assignment
```

**Comment by theelous3** [comment]
Ah, good. Am intentionally not catching all exceptions in a particular place to root out odd ones like this. Hope you don't mind being a bit of a guinea pig there :P

I'll patch this case tonight.

**Comment by jmehnle** [comment]
I have a need for this as well. Let me know if there's anything I can help with. If you have work in progress, a preliminary PR could be useful.

**Comment by PortWhisperer** [comment]
Can anyone explain how to use this parameter to mimic ssl_verify=False? With trio+asks I'm getting SSLEOFERRORs when trying to connect to an HTTPS server that's using a self-signed certificate. I'm not able to find any information on how to get around this error, but it seems related to the SSL verification step. When i try to connect to the same domain with requests using ssl_verify=false there's no issue.

**Comment by omarryhan** [comment]
I'm using the `Session.request` method and can't find a way to disable SSL for a single call. It's not mentioned in the docs unfortunately. What's the correct way to do it? Thanks
