### ISSUE TITLE
TypeError when decompressing streamed response

### ISSUE THREAD

**Issue by tilboerner** [theelous3/asks#78]
Using `StreamBody` as data in `http_utils.decompress` does not work, because the builtin tools expect a byte-like object.

#### StreamBody's journey through `decompress`:

https://github.com/theelous3/asks/blob/074b851ae2ded3ed9968542ad19c5fbb95828228/asks/response_objects.py#L80-L82

https://github.com/theelous3/asks/blob/074b851ae2ded3ed9968542ad19c5fbb95828228/asks/http_utils.py#L31-L36

#### Resulting TypeError:

```
$ cat | python
import asks, trio

async def main():
    r = await asks.get('https://google.com/', stream=True)
    assert r.headers.get('content-encoding')
    r.text

asks.init('trio')
trio.run(main)
```

```
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>

[ trio and other external calls]

  File "<stdin>", line 6, in main
  File ".../lib/python3.6/site-packages/asks/response_objects.py", line 103, in text
    return self._decompress(self.body, self.encoding)
  File ".../lib/python3.6/site-packages/asks/response_objects.py", line 82, in _decompress
    r = decompressor.send(body)
  File ".../lib/python3.6/site-packages/asks/http_utils.py", line 36, in decompress
    data = _compression_mapping[compression](data)
  File "/usr/lib/python3.6/gzip.py", line 531, in decompress
    with GzipFile(fileobj=io.BytesIO(data)) as f:
TypeError: a bytes-like object is required, not 'StreamBody'
```

**Comment by theelous3** [comment]
I'll fix this to fail more gracefully, however note that trying to get the `.text` of a stream doesn't seen the best idea :D

**Comment by theelous3** [comment]
I know that requests allows `.text`ing here, but I really don't see how you can take that and apply it to real streaming use cases. I'm open to ideas however.

**Comment by tilboerner** [comment]
> trying to get the .text of a stream doesn't seem the best idea :D

I suppose. :) Note that the same error happens to `.content`, which just passes through the StreamBody when there's no `content-encoding`. 

> requests allows `.text`ing here

I see two ways to handle this:

1. Enforce the streaming context and deny access to the 'unstreaming' properties, gracefully, early, and consistently. This forces the client code to be mindful of the situation and protects from errors down the road.

2. Transparently 'unstream' and decode, to keep the interface consistent.

I agree that (2) seems unnecessary, given that streaming is always a concious choice by the user. Anyway, in either situation it might help to have a different response class for streaming. It keeps things neatly separated code-wise, so nobody needs to check if there's a StreamBody present. (At least, a `response.is_streaming` might come in handy.) The stream response could just not have the questionable properties in the first place.

I don't know the reasons why `requests` chose (2); they might be good reasons. :) Anyway, `asks` doesn't need to mirror requests in every detail. But the choice should be made, to make the interface consistent and its behavior easier to predict.

**Comment by theelous3** [comment]
Yeah agreed. Stream response obj throwing regular errors is the most reasonable.

**Comment by theelous3** [comment]
Alrighty, https://github.com/theelous3/asks/commit/cbc46f66a99b8f090816ffeb561570d3c5e73329

When you set streaming, you get back a `StreamResponse`, which just doesn't have the `.content` etc.

Discovered some more weirdness about requests and streaming in the mean time. I think sensibility was sacrificed for the sake of "the api". Won't be mirroring the behavior there surrounding streams. (Using `.content` does network io, wat? Bad!)
