### ISSUE TITLE
Make Response objects usable as async context managers

### ISSUE THREAD

**Issue by t-8ch** [theelous3/asks#79]
It would be nice if the `Response` object would implement the async context manager protocol, even as a NOOP.
When migrating from aiohttp/requests code often treats responses as such and this would reduce the migration friction to `asks`.
Furthermore it would futureproof usercode in case future, more sophisticated `Response` object actually need resource managers.

**Comment by theelous3** [comment]
Sure, why not :)

Note, in case you didn't see, the `.body` of a response is an async context manager when `stream=True`, with `async for` impl.

**Comment by t-8ch** [comment]
I did notice :-)
My usecase was mostly to port some code from asyncio/http to trio/asks.
The codebase used responses as contextmanager and I did not want to shuffle the code around too much. (The nurseries where not problematic as the code was already using a custom, similar abstraction.)

Will send a PR.

**Comment by theelous3** [comment]
booya
