### ISSUE TITLE
convenience method `Response.raise_for_status()`

### ISSUE THREAD

**Issue by carlwgeorge** [theelous3/asks#82]
requests `Response` objects have an `raise_for_status()` method that I enjoy using.

http://docs.python-requests.org/en/master/api/#requests.Response.raise_for_status

Please implement this in asks.

**Comment by carlwgeorge** [comment]
https://github.com/requests/requests/blob/v2.19.1/requests/models.py#L916-L939

**Comment by theelous3** [comment]
This is planned. I'll get around to it this week :)

**Comment by theelous3** [comment]
I just read your other comment. If you'd like to impl, by all means PR this puppy.

**Comment by carlwgeorge** [comment]
Sorry for the delay, submitted as #92.
