### ISSUE TITLE
Behavior of timeout when streaming

### ISSUE THREAD

**Issue by cmehay** [theelous3/asks#86]
Hello there, 

`timeout` seems to apply only on connection but not on received data when `stream` is enabled.

Here an example:

`server.py`
```python
import time
from flask import Flask, Response

app = Flask(__name__)


@app.route('/')
def ping():
    def generate():
        while True:
            yield "PING\n"
            time.sleep(10)
    return Response(generate(), mimetype='text/plain')
```

run this 
```shell
$ FLASK_APP=server.py flask run
```
Server will echo PING every 10 seconds

`asks_test.py`
```python
import asks
import trio

asks.init('trio')


async def test_timeout():
    r = await asks.get(
        'http://localhost:5000/',
        stream=True,
        timeout=5,
        retries=0,
    )

    async for line in r.body:
        print(line)


trio.run(test_timeout)
```
The connection should timeout after 5 seconds, but it doesn't.

```shell
$ python asks_stream_timeout.py
bytearray(b'PING\n')
bytearray(b'PING\n')
bytearray(b'PING\n')
```

There is no way to handle a connection lost in this case.

I'm starting learning using async development with python, but I don't find a workaround using trio to handle a timeout if the connection has been lost.

**Comment by theelous3** [comment]
Hey sorry didn't get a chance to respond to you till now :)

So, from my perspective, I don't think we want the timeout to actually apply across the entire lifetime of the connection. Our goal with (that) timeout is to make sure we get a connection to the server, and a response of some kind.

With a stream response, it may be the case that you
1. Connect to something with `timeout=1, stream=True`
2. Get a response instantly
3. Do nothing with the active connection for 10 seconds.
4. ???

Should it instantly error when you go to read? There could be no problem whatsoever with the connection, but if we treat the whole operation from initial request to end of stream body as atomic, then it should break in the above case, which we do not want.

It's better to manage the reads individually. For this, you can use trio/curio's timout manager.

`curio.timeout_after` or `trio.fail_after`

**Comment by cmehay** [comment]
The real problem in this case is that is impossible to handle a connection lost. If the connection has been lost by network issue, it will hang forever in the `for` loop in my example.

The behavior of `requests` is to raise a timeout exception if no data has been received after the timeout.

Well, I cogitated a little and find a way to handle timeout using trio:

```python
import asks
import trio

asks.init('trio')


async def iter_timeout(aiter, timeout):
    i = aiter.__aiter__()
    while True:
        try:
            with trio.fail_after(timeout):
                yield await i.__anext__()
        except StopAsyncIteration:
            break


async def test_timeout():
    r = await asks.get(
        'http://localhost:5000/',
        stream=True,
        retries=0,
    )

    async for line in iter_timeout(r.body, timeout=11):
        print(line)


trio.run(test_timeout)
```

Hope this will be helpful to someone :smile:

**Comment by theelous3** [comment]
I must've been on drugs reading your example earlier. I see what  you mean now. I'll make `.body` a property so that if a timeout is passed to it, it will apply to each request for more data.

`async with r.body(timeout=5):`

That kinda thing. Nice catch.

**Comment by theelous3** [comment]
nvm it's on pypi now :)
