### ISSUE TITLE
Test support / mocking

### ISSUE THREAD

**Issue by bradwood** [theelous3/asks#93]
Hi,

A bit of a newbie question:

Is there an easy way to mock an asks response in my tests?

Ta

Brad

**Comment by theelous3** [comment]
Oh, by the way, grab an irc client, join the freenode server, and join the ##learnpython channel :)

We can help with all of these little questions there.

**Comment by bradwood** [comment]
Thanks @theelous3 -- I ended up spinning up a small HTTP server in a fixture that pretty much does what your snippet above does... My question was not about mocking generally, which I understand reasonably well, but more about whether the library provided any specific support for testing? A bit like `responses` does for `requests` or `aresponses` does for `aiohttp`.

I appreciate the time you took in replying.

**Comment by theelous3** [comment]
Ah, nope. I am working on something at the moment for asks' tests, as a way to improve them.

You can see some examples here, with a test example at the bottom. Contibs welcome over there of course. Locally I'm implementing cookie stuff for it as we speak.

https://github.com/theelous3/overly/blob/master/example.py#L79

(It's formatted for terminal output so the test code its self has some ugly prints. Ignore :D Sounds like something you might be interested in.
