### ISSUE TITLE
Chunked and encoded gzip not decompressing correctly in streams

### ISSUE THREAD

**Issue by theelous3** [theelous3/asks#96]
From https://github.com/theelous3/asks/issues/95 specifically https://github.com/theelous3/asks/issues/95#issuecomment-435187332

The gzip module blows and isn't sophisticated enough to decompress streams. Drop it in favour of full zlib.

https://docs.python.org/3/library/zlib.html#zlib.decompress
https://stackoverflow.com/a/22311297

**Comment by gmacon** [comment]
I bumped into this today, and I found a work-around: I added `("Accept-Encoding", "identity")` to the request headers to prevent the server from sending me compressed data.

I noticed that #157 has merge conflicts; I'd be happy to rebase it onto the latest master if other folks don't think they'll have time.

**Comment by theelous3** [comment]
@gmacon Yes! I'm super swamped at a new position and haven't/won't have time for a while. Please feel free to repair the pr :)
